# use Gitpod's official Python image
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # update & install Xvfb so GUIs can run
      sudo apt-get update
      sudo apt-get install -y xvfb
      # install your Python deps
      pip3 install -r requirements.txt

  - command: |
      # start a virtual display and run your game
      xvfb-run --auto-servernum python3 maze_game.py
